theme: jekyll-theme-hacker
title: Insert Title Here
description: Blah blah
show_downloads: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
include: ["_posts"]

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
